[build]
  command = "npm run build"
  base = "site"
  publish = "dist"

[[redirects]]
  from = "/about"
  to = "/"
  status = 301
  
[[redirects]]
  from = "/card"
  to = "/"
  status = 301
  
[[redirects]]
from = "https://marisamorby.com/newsletter"
to = "https://marisamorby.ck.page/posts/"
status = 200
force = true

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
