<?php

namespace Roots\Sage\Extras;

use Roots\Sage\Setup;

/**
 * Add <body> classes
 */
function body_class($classes) {
  // Add page slug if it doesn't exist
  if (is_single() || is_page() && !is_front_page()) {
    if (!in_array(basename(get_permalink()), $classes)) {
      $classes[] = basename(get_permalink());
    }
  }

  // Add class if sidebar is active
  if (Setup\display_sidebar()) {
    $classes[] = 'sidebar-primary';
  }

  return $classes;
}
add_filter('body_class', __NAMESPACE__ . '\\body_class');

/**
 * Clean up the_excerpt()
 */
function excerpt_more() {
  return ' &hellip; <a href="' . get_permalink() . '">' . __('Continued', 'sage') . '</a>';
}
add_filter('excerpt_more', __NAMESPACE__ . '\\excerpt_more');

/**
 * Enable SVG uploads
 */
function enable_svg_uploads( $mimes ) {
  $mimes['svg'] = 'image/svg+xml';
  return $mimes;
}
add_filter('upload_mimes', __NAMESPACE__ . '\\enable_svg_uploads');


/*
 * Shortcode to create buttons.
 */
function mm_shortcode_button( $atts, $content ) {
  if (!isset($atts['href'])) {
    return '';
  }

  return sprintf('<a href="%s" class="button button--dark">%s</a>', $atts['href'], $content);
}
add_shortcode('button', __NAMESPACE__ . '\\mm_shortcode_button');

/*
 * Add custom options pages
 */
function add_acf_options_pages() {
  if (!function_exists('acf_add_options_page')) {
    return;
  }

  acf_add_options_page(array(
    'page_title' => 'Website Self-Assessment Settings',
    'menu_title' => 'Website Assessment',
    'parent_slug' => 'options-general.php',
  ));

  acf_add_options_page(array(
    'page_title' => 'Website Shared Copy',
    'menu_title' => 'Website Shared Copy',
    'parent_slug' => 'options-general.php',
  ));
}
add_action('after_setup_theme', __NAMESPACE__ . '\\add_acf_options_pages');

/**
 * Add custom field groups
 */
function add_acf_field_groups() {
  if (!function_exists('acf_add_local_field_group')) {
    return;
  }

  /*
   * Marisa Facts
   */
  acf_add_local_field_group(array (
    'key' => 'group_570fa5453fd35',
    'title' => 'Marisa Facts',
    'fields' => array (
      array (
        'key' => 'field_570fa54970b89',
        'label' => 'Fact Number',
        'name' => 'fact_number',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => 15,
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => 1,
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_570fa56b70b8a',
        'label' => 'Fact',
        'name' => 'fact',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => 85,
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => 75,
        'readonly' => 0,
        'disabled' => 0,
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'facts',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

  /*
   * Flexible Content Blocks for the Home Page
   */
  acf_add_local_field_group(array (
    'key' => 'group_5722e270a892b',
    'title' => 'Home Page',
    'fields' => array (
      array (
        'key' => 'field_5722e289ad6ae',
        'label' => 'Sections',
        'name' => 'sections',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'button_label' => 'Add Section',
        'min' => '',
        'max' => '',
        'layouts' => array (
          array (
            'key' => '5722e2ac70270',
            'name' => 'text',
            'label' => 'Text Section',
            'display' => 'block',
            'sub_fields' => array (
              array (
                'key' => 'field_5722e2cbad6af',
                'label' => 'Heading',
                'name' => 'heading',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_5722e2dbad6b0',
                'label' => 'Body Content',
                'name' => 'body_content',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'basic',
                'media_upload' => 1,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          array (
            'key' => '5722e308ad6b1',
            'name' => 'company_logos',
            'label' => 'Company Logos',
            'display' => 'block',
            'sub_fields' => array (
              array (
                'key' => 'field_5722e322ad6b2',
                'label' => 'Heading',
                'name' => 'heading',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_5722e32dad6b3',
                'label' => 'Companies',
                'name' => 'companies',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'collapsed' => '',
                'min' => '',
                'max' => '',
                'layout' => 'table',
                'button_label' => 'Add Company',
                'sub_fields' => array (
                  array (
                    'key' => 'field_5722e371ad6b5',
                    'label' => 'Company Logo',
                    'name' => 'logo',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => 25,
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                  ),
                  array (
                    'key' => 'field_5722e33dad6b4',
                    'label' => 'Company Name',
                    'name' => 'name',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => 55,
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                  ),
                  array (
                    'key' => 'field_5722e3c1ad6b6',
                    'label' => 'Relationship',
                    'name' => 'relationship',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => 20,
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array (
                      'featured' => 'Featured In',
                      'client' => 'Worked With',
                    ),
                    'default_value' => array (
                      0 => 'featured',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'disabled' => 0,
                    'readonly' => 0,
                  ),
                ),
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          array (
            'key' => '5722e416ad6b7',
            'name' => 'client_testimonials',
            'label' => 'Client Testimonials',
            'display' => 'block',
            'sub_fields' => array (
              array (
                'key' => 'field_5722e427ad6b8',
                'label' => 'Heading',
                'name' => 'heading',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_5722e42bad6b9',
                'label' => 'Testimonials',
                'name' => 'testimonials',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'collapsed' => '',
                'min' => '',
                'max' => '',
                'layout' => 'block',
                'button_label' => 'Add Testimonial',
                'sub_fields' => array (
                  array (
                    'key' => 'field_5722e491ad6bb',
                    'label' => 'Photo',
                    'name' => 'photo',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => 30,
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                  ),
                  array (
                    'key' => 'field_5722e4b6ad6bc',
                    'label' => 'Name',
                    'name' => 'name',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => 35,
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                  ),
                  array (
                    'key' => 'field_5722ea41ad6bd',
                    'label' => 'Company/Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => 35,
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                  ),
                  array (
                    'key' => 'field_5722e442ad6ba',
                    'label' => 'Quote',
                    'name' => 'quote',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 1,
                  ),
                ),
              ),
            ),
            'min' => '',
            'max' => '',
          ),
        ),
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page',
          'operator' => '==',
          'value' => '414',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array (
      0 => 'the_content',
      1 => 'excerpt',
      2 => 'custom_fields',
      3 => 'discussion',
      4 => 'comments',
      5 => 'revisions',
      6 => 'author',
      7 => 'format',
      8 => 'page_attributes',
      9 => 'categories',
      10 => 'tags',
      11 => 'send-trackbacks',
    ),
    'active' => 1,
    'description' => '',
  ));

  /*
   * Website Self-Assessment (questions and messages)
   */
  acf_add_local_field_group(array (
    'key' => 'group_57299e59b4bfd',
    'title' => 'Website Assessment Settings',
    'fields' => array (
      array (
        'key' => 'field_5729a74139a18',
        'label' => 'Assessment Questions',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'left',
        'endpoint' => 0,
      ),
      array (
        'key' => 'field_57299e6d1a782',
        'label' => 'Questions',
        'name' => 'questions',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => '',
        'max' => '',
        'layout' => 'block',
        'button_label' => 'Add Question',
        'sub_fields' => array (
          array (
            'key' => 'field_57299e7f1a783',
            'label' => 'Question ID',
            'name' => 'id',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => 15,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
          ),
          array (
            'key' => 'field_57299f081a784',
            'label' => 'Question',
            'name' => 'question',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => 45,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
          ),
          array (
            'key' => 'field_57299f361a785',
            'label' => 'Instructions',
            'name' => 'instructions',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => 40,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 2,
            'new_lines' => '',
            'readonly' => 0,
            'disabled' => 0,
          ),
          array (
            'key' => 'field_57299f6e1a786',
            'label' => 'Answers',
            'name' => 'answers',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'collapsed' => '',
            'min' => 1,
            'max' => 5,
            'layout' => 'table',
            'button_label' => 'Add Answer',
            'sub_fields' => array (
              array (
                'key' => 'field_57299f8e1a787',
                'label' => 'ID',
                'name' => 'id',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 20,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_57299fa01a788',
                'label' => 'Label',
                'name' => 'label',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 60,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_57299fbe1a789',
                'label' => 'Value',
                'name' => 'value',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 20,
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  0 => 'Bad',
                  1 => 'Okay',
                  2 => 'Good',
                ),
                'default_value' => array (
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'disabled' => 0,
                'readonly' => 0,
              ),
            ),
          ),
          array (
            'key' => 'field_5729bca367bd8',
            'label' => 'Resource',
            'name' => 'resource',
            'type' => 'file',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => '',
          ),
        ),
      ),
      array (
        'key' => 'field_5729a75539a19',
        'label' => 'Assessment Results Messages',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'left',
        'endpoint' => 0,
      ),
      array (
        'key' => 'field_5729a35ba96c0',
        'label' => 'Messages',
        'name' => 'messages',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => 'field_5729a454a96c2',
        'min' => 1,
        'max' => 0,
        'layout' => 'block',
        'button_label' => 'Add Message',
        'sub_fields' => array (
          array (
            'key' => 'field_5729a373a96c1',
            'label' => 'Minimum Score',
            'name' => 'minimum_score',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => 15,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '%',
            'min' => 0,
            'max' => 100,
            'step' => 1,
            'readonly' => 0,
            'disabled' => 0,
          ),
          array (
            'key' => 'field_5729a80039a1d',
            'label' => 'On-Page Results Message',
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => 'This is the message that\'s displayed after all the questions have been answered. This is where you show the initial score and nudge for the email opt-in.',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
          ),
          array (
            'key' => 'field_5729a454a96c2',
            'label' => 'Heading',
            'name' => 'heading',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => 40,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
          ),
          array (
            'key' => 'field_5729a474a96c3',
            'label' => 'Subheading',
            'name' => 'subheading',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => 40,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
          ),
          array (
            'key' => 'field_5729a47ca96c4',
            'label' => 'Message',
            'name' => 'message',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => '',
            'readonly' => 0,
            'disabled' => 0,
          ),
          array (
            'key' => 'field_5729a4c2a96c5',
            'label' => 'Image',
            'name' => 'image',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'collapsed' => '',
            'min' => 1,
            'max' => 1,
            'layout' => 'block',
            'button_label' => 'Add Image',
            'sub_fields' => array (
              array (
                'key' => 'field_5729a4e6a96c6',
                'label' => 'URL',
                'name' => 'src',
                'type' => 'url',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 40,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
              array (
                'key' => 'field_5729a507a96c7',
                'label' => 'Description',
                'name' => 'alt',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 30,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_5729a51ea96c8',
                'label' => 'Caption (defaults to description)',
                'name' => 'caption',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 30,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_5729a549a96c9',
                'label' => 'Credit',
                'name' => 'credit',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 50,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_5729a55fa96ca',
                'label' => 'Credit Link',
                'name' => 'creditLink',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 50,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
            ),
          ),
          array (
            'key' => 'field_5729a81539a1e',
            'label' => 'Email Results Message',
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => 'This is the email message that will be delivered to people who opt-in.

  You can customize each message as needed. The resources will be added under each heading according to the person\'s score for that question.',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
          ),
          array (
            'key' => 'field_5729a83039a1f',
            'label' => 'Subject Line',
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 'Your Assessment Results',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
          ),
          array (
            'key' => 'field_5729a85739a20',
            'label' => 'Message',
            'name' => 'email_message',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'collapsed' => '',
            'min' => 1,
            'max' => 1,
            'layout' => 'row',
            'button_label' => 'Add Row',
            'sub_fields' => array (
              array (
                'key' => 'field_5729a8ad39a21',
                'label' => 'Top',
                'name' => 'top',
                'type' => 'textarea',
                'instructions' => 'Use MailChimp-style merge tag <code>*|FNAME|*</code> to insert the person\'s first name.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => 'Hey, *|FNAME|*–

  This is an overview of what this report details.

  You can read it first, or start clicking links like a pyschopath.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_5729a8ce39a23',
                'label' => 'Bad Score Resource Header',
                'name' => 'badHeading',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => 'Critical Fixes:',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_5729a8fb39a24',
                'label' => 'Okay Score Resource Header',
                'name' => 'okayHeading',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => 'Fixes to Consider:',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_5729a91639a25',
                'label' => 'Good Score Resource Header',
                'name' => 'goodHeading',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => 'These Things Are All Good, But Feel Free to Review:',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_5729a8bf39a22',
                'label' => 'Bottom',
                'name' => 'bottom',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => 'If you have any questions, just reply to this message. I\'d love to hear from you.

  Talk soon,
  Marisa Morby',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
            ),
          ),
        ),
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-website-assessment',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

  /*
   * Header and Footer editable text
   */
  acf_add_local_field_group(array (
    'key' => 'group_57303fac10560',
    'title' => 'Website Copy',
    'fields' => array (
      array (
        'key' => 'field_573040ab5bf50',
        'label' => 'Header',
        'name' => 'header',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'left',
        'endpoint' => 0,
      ),
      array (
        'key' => 'field_573040c05bf52',
        'label' => 'Tagline (Cursive Words)',
        'name' => 'header_tagline_cursive',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => 50,
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Make your customers',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_5730410a5bf53',
        'label' => 'Tagline (Bold Words)',
        'name' => 'header_tagline_bold',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => 50,
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Happier',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_5730411b5bf54',
        'label' => 'Button Text',
        'name' => 'header_button_text',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => 50,
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Find Out How',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_573041315bf55',
        'label' => 'Button Link',
        'name' => 'header_button_link',
        'type' => 'page_link',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => 50,
          'class' => '',
          'id' => '',
        ),
        'post_type' => array (
          0 => 'page',
        ),
        'taxonomy' => array (
        ),
        'allow_null' => 0,
        'multiple' => 0,
      ),
      array (
        'key' => 'field_573040bc5bf51',
        'label' => 'Footer',
        'name' => '_copy',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'left',
        'endpoint' => 0,
      ),
      array (
        'key' => 'field_573041735bf56',
        'label' => 'Heading',
        'name' => 'footer_heading',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'I love to get people talking to each other.',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_5730418e5bf57',
        'label' => 'About Text',
        'name' => 'footer_about_text',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
      ),
      array (
        'key' => 'field_573041c15bf58',
        'label' => 'Button Text',
        'name' => 'footer_button_text',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => 50,
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Find Out How',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_573041d55bf59',
        'label' => 'Button Link',
        'name' => 'footer_button_link',
        'type' => 'page_link',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => 50,
          'class' => '',
          'id' => '',
        ),
        'post_type' => array (
          0 => 'page',
        ),
        'taxonomy' => array (
        ),
        'allow_null' => 0,
        'multiple' => 0,
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-website-shared-copy',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));
}
add_action('after_setup_theme', __NAMESPACE__ . '\\add_acf_field_groups');
